### ISSUE TITLE
Button click is not working

### ISSUE THREAD

**Issue by fenalivora** [Naresh5/ChatBox#6]
Hi Naresh, 

Please look into the main activity. I can't see the button click. Please added into the java file. So that I can work on API call. Thanks

**Comment by Naresh5** [comment]
Hello Fenali, We are working on that. Once I'll be done, will inform you !!!Happy coding

**Comment by Naresh5** [comment]
Hello there,
I have fixed an issue that you had created.
Now you can have the latest code and you may continue further development.

Thanks.
Happy  Coding.
